name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        chrome-version: ["latest"]

    steps:
      # Setup Repository
      - uses: actions/checkout@v2

      # Setup Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Setup Chrome
      - name: Use Chrome ${{ matrix.chrome-version }}
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome-version }}
      - run: chrome --version

      # Execute tests
      # - run: npm ci
      - run: npm test
        env:
          PORT: "8080"
